#+TITLE: My New Favorite: Darker Than Black
#+AUTHOR: Ryan
#+EMAIL: ryan@ryanmj.xyz
#+OPTIONS: num:nil

Quarantine boredom finally caught up to me last month and I was desperately looking for some new entertainment. Desperate times call for desperate measures: after six years of not watching any anime I decided to give Japanese cartoons another shot. I am 'back on my bullshit' as the kids say.

A then friend recommended me one of his favorite anime: /Darker Than Black/. I was a bit hesitant as I had never heard of it before, and I still haven't seen some of the great anime classics like /Evangelion/ or /Akira/ yet, but my friend is like me, he has good taste, so I trusted his judgment. What I watched is now easily my favorite anime of all time - and perhaps my favorite T.V. show as well! Great characters, great animation, fantastic music, and stylish as hell /Darker Than Black/ stands with likes of /Cowboy Bebop/  and /Trigun/ as one of the great anime classics. [fn::All the normies reading this should know that the show is currently on Hulu.]

So you can imagine my disappointment when I watched the vastly inferior second season - with its boring, generic anime soundtrack, occasionally cringe inducing characterization, and that *_/terrible/_* ending! None of /The Black Contractor/'s style and about half of its substance! After finishing Season 2 all I could think of is unjust it is that *this* was /Darker Than Black/'s one shot a sequel.  And I do need to emphasize that this was  /Darker Than Black's one shot a sequel/. Because of the show's obscurity it's not likely to  ever receive any followup, /at most/ we'll get a new manga. 

All of this sounds like I hate Season 2, but I actually don't! Half of the substance of the best T.V. show ever created is still quite a lot after all. /Gemini of the Meteor/ has its powerful moments, and few powerful themes to go along with it as well. 

** /Gemini of the Meteor/ rewritten
NOTE:WRITE IT AS IT'S COMING TO YOU IN YOUR HEAD. WRITE ANALYSIS AS YOU GO.
